---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1n7wuslev8mne367vtlgsmefzur7yfvwtaw8kftc4vf3dq0gv2adsufyy2g
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1n7wuslev8mne367vtlgsmefzur7yfvwtaw8kftc4vf3dq0gv2adsufyy2g
