---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1nx9xkrl50c9netcqze9ntp2tqk30jkgdwcd4s6yhrk2e8ns6298q4ppn00
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1nx9xkrl50c9netcqze9ntp2tqk30jkgdwcd4s6yhrk2e8ns6298q4ppn00
