kind: ENC[AES256_GCM,data:dodKUJ8Q,iv:pZvn8veBYkxwztDGkIJKMO6R3Bq6ktQ/TUMn3xbsfGY=,tag:VAIMAtyszbzx55KMdq+8PQ==,type:str]
ansible_user: ENC[AES256_GCM,data:LDFUuyc8,iv:kevwfJ35OUBysig0WRwbhx+V64NmHkVJing0YAxL1F0=,tag:3ppEPmglj80OYCVI5BjfgA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:9nya9tEDk9k=,iv:LKQhlsAp9XJObYmn4h6R1t7V80mR4wkodvj5TeInx2I=,tag:5q7wHm2ewTHQgMEIGL3DVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7wuslev8mne367vtlgsmefzur7yfvwtaw8kftc4vf3dq0gv2adsufyy2g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzL3haalo0SmIwa0prYk9O
            c2pGRmxZbnF1YzFMNkJiUjRSZlJySkx4bVd3CjRCaFlHTE1hUGViMG1TTWlXYWFa
            b2EzV0xwZU1ST1ovV0VTbngxZWZETUkKLS0tIEhMTlJTUUpRbWpZbDRPUWZoVUJT
            b3BudEZCMVZ4WGNuclZvVmlONmZ4L00KL1U2MVS2PjaZyBDj08f+YaHHSAgdonyS
            akLIJwMCPO522PKEu1kYZIDofr9uyeTYnS25r+/6DuubKJ8P17F7kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-03T06:08:33Z"
    mac: ENC[AES256_GCM,data:YLrQZkNbI9equn5wG3bZ9AAGwh5KV9NRIcv10neLJ7DhXRIUrz6+8UlDAa+jmznqlsg+HP8HRWex1f4aAESGsF/0pR7MJFKkARlfvid/yx3OUwRiJg57gCTz3xrgR+xWlZTieudl5DRXW6Khxh+UfN6HLiDRBRfaeYA1ZocSHJE=,iv:U8M16yByQXVuQZ/Dc1Pl3kJZMqgAq9mZZzgYY9KQfHk=,tag:l2QtJ8YnmXMysmD5RlFAFw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
