kind: ENC[AES256_GCM,data:0HZrXyuS,iv:fkN77zFOhQ2n17aOxZRI8pz4dJ8VKo0DaZ+NcBTfFWo=,tag:qlKdliDEE6TNNp3Aeo1CiQ==,type:str]
ansible_user: ENC[AES256_GCM,data:ZHc2G0uI,iv:x1BT39jFdnxfq4mf1qfs5OqCmp1cIsE/ii+n+GdQECY=,tag:BIZizOg1FlF1mZGb/nmKXw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:kgt7vEMsJSY=,iv:r3yDfCM393HTxJo6uRYCLOJQj85EShp99eNBnRYXy9o=,tag:EuTHInxqnafVoQBMzcXYCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9xkrl50c9netcqze9ntp2tqk30jkgdwcd4s6yhrk2e8ns6298q4ppn00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZFhRSkVYZ0h5SkpHRVRN
            dnZkSkZ3M2lNUzV0VVpSL21VUFhJWEhWalMwCk81OVlJTkhjZDgzYnByR0VUN1Z6
            RkVYZWhKRkVhakRlR2ZoOU5IOW9BancKLS0tIHlCWmp5RWVQakxHR29TWGN1Q1N1
            ODM0NmVCN3dZM0U4YThhZ1FvbDlSL3MKY1Q52p9nX3Jk4+nhKnvzDiQOpDgi/Efm
            ya3NiJB8vyH4Tr8dZQYKsaTOzB9yXDtTX1s2O6jnuU12E+8lPGzoCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-03T05:50:48Z"
    mac: ENC[AES256_GCM,data:ncjTFjJfVA8aMSUIEo29nvE16YQyU8MqIafC5xA7ZYHErFkGeL/OJQ/r9GSafV7GsgaeBf6JVpyTuO9z8iAjYPgOJNJ88JawO8p17mUBkeLlpKVwOpWUmQt9x9QCWJc+X9DxGweS54J6hcrJcHCG59HzUtF1p+aJcTQ6lQhTig4=,iv:poZEMfnh8HwqX1vE8e/ye0GnOvGTSjNQFte2P495qsU=,tag:rJYXm4/O8pDSsOE9jmsI5A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
