apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:Hs/0ybs=,iv:UtJUNrk9JlUEdK952oDkrL328AFXBUJPc12jduaRcXs=,tag:eBGKE2TDCi0VutwEWViioA==,type:str]
    admin-password: ENC[AES256_GCM,data:bJbDzbqp91QIQW++It0TP1pVszhUA0Zl,iv:L1x7WuhVVWsZ+R63EYU9fPIXj80ejiGLSvOv7lcr9nE=,tag:fEQOv8tDWVE4+iv+/zsG7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7wuslev8mne367vtlgsmefzur7yfvwtaw8kftc4vf3dq0gv2adsufyy2g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeE9ZNHdNZUFTWjV1LzBj
            c2ZCWTRLTzBQMWgwQ1NEdkRhS054UUd3aDBNCkE0K2NDNXpGckIxSjdJYXNpZGpm
            YnR0SFhKb29PMjd6cGhwTENxdDI1WTQKLS0tIG5jdzVlbURqK3pRTTg5c0I3TGhp
            TjJhQ2hhZkdWZ2FGaU00ZU43UGxBNVkK3OQBFGyTsYAHKogP2ZGpURsvL/vK4dH8
            P9C49D5bGRxiRRGksJGG9qgLAuEDqGrFQEFPerwHv+J9GqSG5EOY9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-03T06:08:33Z"
    mac: ENC[AES256_GCM,data:HkdJh12j79yJzcd3oqzjJRlPoFOJMx6x2zLs55L2X5xltQWefWbyCLJKcBFI1IczX1syoUkhRMvEJz91ab9jFG4DuJFNTpu355W6TNBJ77YN/a8WSYjEB39dOUWK8XUqT+lVioPFYVaEk0GS4S6TMHtOyJ1d45llAXZfY2GWCLo=,iv:pi/+3KHeYfMgedt3PsXwiWTgqR2k2tGtS7fGQUaDqVg=,tag:1RBDrWEuS4ARhs+UXDNnDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
