apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:l4zB+rivKUP4dehbEIYUQ18lNw==,iv:HbtFkB0aX49ZL8ALJBxSsiOLa8tlTLC1zxHc0KSBDVM=,tag:cJCZ2MDpTVmPUER1V/baUQ==,type:str]
    api-key: ENC[AES256_GCM,data:Exh5H1/aKpJfE6meLVW8bgcy/fqKYhZUl+l3JFsXIjwgoJN15A==,iv:EiG9FGw9SNwibVPrWFAe1GciBZE7gRFn2+qGCHWWrps=,tag:EaKGmr0IPmG7JUzJvfxvbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9xkrl50c9netcqze9ntp2tqk30jkgdwcd4s6yhrk2e8ns6298q4ppn00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TGVqNDFhNG1NcHdCUFRl
            TzBWbU83Vmxnd1dickxWWUhBSVd1UlZBZm04Cng0VEtXWldyQ2t0d2pYMFZDdFRU
            SEs1SlQyd21qYVBTUWVuTXhuZ1cvZ1UKLS0tIElobi9XT1czYXJZNWxURUFTNG4r
            eVNYaWg3L1BpcUVGdlZBZ0htYUZpUUUKAT3O8aR+1SQsm6FJ+qSJc7KN3LPMeDvR
            Ptf6R1PYsg0qLu9u6tiBtj1kFFb+H8pFisOCbQRQgLfQ/fMc1Sj9ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-03T05:50:48Z"
    mac: ENC[AES256_GCM,data:uWnIgJ4aYwjw2xWQyKV3p5LpiNY9XH+UNRrNdLAVEl66s49U/Gp06SJkWe9D7SJsYyN5ht1i3NwxYERHP9zFbnq4RemhZTLt5NvUA2cA+alglYlQdDBeaJR1LkyxtVCTzvR6pOUP4E2X+y1yl4oS7c4M9W4jzNZI9xE2eic/dFg=,iv:bPZUzAvOK6fAo0jMGrZYHJKlJ/3a/ZEUwwbBv6UWmhA=,tag:xXKVu1QQ88bmqLrc7vg45A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
