apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:zaI7k0XmrAnfVGmsjSFC3TiUPWBD60uJnW2WwZ9Rw87/ShfeKyQCxQ5rkwSPtvSuPG8NO6B4QMOQxCNf,iv:uSa1tgaxacU+QyalrYsX8XIcv4u2XFUKvX3ZUKUI9LM=,tag:121Byx6RVCRCV0yqLNeLWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9xkrl50c9netcqze9ntp2tqk30jkgdwcd4s6yhrk2e8ns6298q4ppn00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybG9PU2tDeDZZT2VXZVdq
            S3dNTEVFVDVaaTNrRmZYOGxpdENuRnN6N0ZJCkxmSTFJUFh4cEk5bVRDcXhIS3F2
            S0NORHVnd1VLdVdCemdmb2s1UUdxU28KLS0tIGdKaGVSRkdBOGJUNFRxcHZnQ1Vj
            L1kzNW9VS0JpUVNPWmR1NTM1MkUvVHMKWGNxeuGWV70dJLL5rmMy18Fatje3nebJ
            Y6Z/hko6tbdVT5/ShRJDKAZXzxHJbSpL2ytnAeGt6k+eDWEQvGGu8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-03T05:50:48Z"
    mac: ENC[AES256_GCM,data:Itrj+3LEG4Yf39Ys/KLblAuW4/pUbF+tMWxpSAexo/Y44P+v61CpNYNZZhFcF5IQXabT+xR1yV8o7m53TeEZkpDu3Iy5MFHbl3SXlzJG9hfVbyOugodj5ZRLZf7bniTiuTclOQUlT2Fq5bUl32ejjkvQh1D+9TQ+vC/nOLTBxWU=,iv:bttWpXv1Z6GZiZkmvFuBBRtPAbqCp2CVLM9TSzr+15A=,tag:6NpFPpNLfyaFYMMBxFnRKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
